##### Basics #####

set-window-option -g mode-keys vi
set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-option -g status off

set -sg escape-time 0

##### Splits #####

bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"


##### Plugins #####

# set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'fabioluciano/tmux-tokyo-night'

set-option -g @clipboard 'wl-copy'

##### Keybindings #####

unbind -n M-j
unbind -n M-k

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# set -g @sessionx-bind 's'
# set -g @sessionx-new 'n'

bind -n M-i if-shell -F "#{==:#{session_name},scratch}" {
    detach
} {
    display-popup -b rounded -h 80% -w 80% -E 'TERM=xterm tmux new-session -A -s scratch'
}

bind -n M-n display-popup -E '
bash -i -c "
  read -p \"Session name: \" name
  tmux new-session -d -s \$name
  tmux switch-client -t \$name
"'

bind s display-popup -E "
tmux list-sessions | sed -E 's/:.*$//' | awk -v cur=\"$(tmux display-message -p '#S')\" '{ if (\$0 == cur) print \$0 \"  ← current\"; else print }' | fzf --reverse | sed 's/ .*//' | xargs tmux switch-client -t
"

bind -n M-g display-popup -E -w 90% -h 90% -b rounded -T "Lazygit" -d "#{pane_current_path}" "lazygit"

##### TPM #####
run '~/.tmux/plugins/tpm/tpm'

##### Appearance #####

set-option -g pane-border-style fg='#1E2229'
set-option -g pane-active-border-style fg='#1E2229'



