bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

set -g mouse on

set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set-option -g @clipboard 'wl-copy'
set -g @plugin 'fabioluciano/tmux-tokyo-night'


set -g @sessionx-bind 's'
set -g @sessionx-new 'n'
set-option -g status off

bind -n M-i if-shell -F "#{==:#{session_name},scratch}" {
    detach
} {
    display-popup -b rounded -h 80% -w 80% -E 'TERM=xterm tmux new-session -A -s scratch'
}

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-window-option -g mode-keys vi
set-option -g renumber-windows on


run '~/.tmux/plugins/tpm/tpm'

set-option -g pane-border-style fg='#1E2229'
set-option -g pane-active-border-style fg='#1E2229'

unbind -n M-j
unbind -n M-k

set -sg escape-time 0
