##### Basics #####

set-window-option -g mode-keys vi
set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-option -g status off

set -sg escape-time 0

##### Splits #####

bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"


##### Plugins #####

# set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'fabioluciano/tmux-tokyo-night'

set-option -g @clipboard 'wl-copy'

##### Keybindings #####

unbind -n M-j
unbind -n M-k
unbind -n M-g

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# set -g @sessionx-bind 's'
# set -g @sessionx-new 'n'

bind -n M-i if-shell -F "#{m:*scratch*,#{session_name}}" {
    detach
} {
    display-popup -b rounded -h 80% -w 80% -d "#{pane_current_path}" -E 'bash -c "TERM=xterm tmux new-session -A -s scratch-$(tmux display-message -p "#S")"'
}

# bind -n M-i run-shell '
#   CURRENT_SESSION=$(tmux display-message -p "#S")
#   CWD=$(tmux display-message -p "#{pane_current_path}")
#   case "$CURRENT_SESSION" in
#     *scratch*)
#       tmux detach
#       ;;
#     *)
#       tmux display-popup -b rounded -h 80% -w 80% -d "$CWD" -T "Scratch ($CURRENT_SESSION)" "tmux new-session -A -s scratch-$CURRENT_SESSION"
#       ;;
#   esac
# '

bind -n M-n display-popup -E '
bash -i -c "
  read -p \"Session name: \" name
  tmux new-session -d -s \$name
  tmux switch-client -t \$name
"'

bind s display-popup -E "
tmux list-sessions | sed -E 's/:.*$//' | grep -v scratch | awk -v cur=\"$(tmux display-message -p '#S')\" '{ if (\$0 == cur) print \$0 \"  ← current\"; else print }' | fzf --reverse | sed 's/ .*//' | xargs tmux switch-client -t
"

bind k run-shell '
  CURRENT=$(tmux display-message -p "##S" | tr -d "\r\n");
  SESSIONS=$(tmux list-sessions -F "##{session_name}" | grep -vFx "$CURRENT");
  if [ -z "$SESSIONS" ]; then
    tmux display-message "No other sessions to switch to";
  else
    NEXT=$(echo "$SESSIONS" | head -n 1);
    tmux switch-client -t "$NEXT";
    tmux kill-session -t "$CURRENT";
  fi
'

bind -n M-g if-shell -F '#{m:gemini,#{session_name}}' { detach-client } { display-popup -E -w 90% -h 90% -b rounded -T "Gemini" -d "#{pane_current_path}" 'tmux new-session -A -s gemini gemini' }

bind -n M-j display-popup -E -w 85% -h 85% -b rounded -T "AI Chat" -d "#{pane_current_path}" 'source /home/saltchicken/.config/tmux/scripts/.venv/bin/activate && llm_plx'

bind g display-popup -E -w 90% -h 90% -b rounded -T "Lazygit" -d "#{pane_current_path}" "lazygit"


##### TPM #####
run '~/.tmux/plugins/tpm/tpm'

##### Appearance #####

set-option -g pane-border-style fg='#1E2229'
set-option -g pane-active-border-style fg='#1E2229'




