-- vim.keymap.set("n", "<leader>ac", ":Augment chat<CR>", { noremap = true, silent = true })
-- vim.keymap.set("v", "<leader>ac", ":Augment chat<CR>", { noremap = true, silent = true })
--
-- vim.keymap.set("n", "<leader>at", ":Augment chat-toggle<CR>", { noremap = true, silent = true })
-- vim.keymap.set("v", "<leader>at", ":Augment chat-toggle<CR>", { noremap = true, silent = true })
vim.keymap.set("i", "<A-f>", function()
  require("neocodeium").accept()
end)
vim.keymap.set("i", "<A-w>", function()
  require("neocodeium").accept_word()
end)
vim.keymap.set("i", "<A-a>", function()
  require("neocodeium").accept_line()
end)
vim.keymap.set("i", "<A-e>", function()
  require("neocodeium").cycle_or_complete()
end)
vim.keymap.set("i", "<A-r>", function()
  require("neocodeium").cycle_or_complete(-1)
end)
vim.keymap.set("i", "<A-c>", function()
  require("neocodeium").clear()
end)

vim.keymap.set("n", "<Tab>", "<cmd>BufferLineCycleNext<CR>", {})
vim.keymap.set("n", "<S-Tab>", "<cmd>BufferLineCyclePrev<CR>", {})
vim.keymap.set("n", "<leader>bd", "<cmd>bdelete<CR>", { desc = "[B]uffer [D]elete" })

vim.keymap.set("n", "<leader>hp", function()
  Snacks.dashboard()
end, { desc = "Show Dashboard" })

-- vim.keymap.set("n", "<leader>db", ":DBUIToggle<CR>", { desc = "Open DBUI" })
